before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
    - build
    - test
    - versions
    - pypi
    - cleanup

variables:
    BUILD_BOX_NAME: $CI_REGISTRY_IMAGE/build-box-gamma

services:
  - docker:20.10.16-dind

Build:
    stage: build
    tags:
      - dind
    only:
      - master
      - merge_requests
      - tags
    script:
        - docker build -t $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA --push .

Units:
    stage: test
    tags:
      - dind
    only:
      - master
      - merge_requests
      - tags
    script:
      - docker pull $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA || true
      - docker run $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA sh -c 'make test'

ReactUnits:
    stage: test
    tags:
      - dind
    only:
      - master
      - merge_requests
      - tags
    script:
      - docker pull $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA || true
      - docker run $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA sh -c 'make jest'

CheckVersion:
    stage: versions
    image: python:3.8
    before_script: []
    script:
      - python check_version.py
    rules:
      - if: $CI_COMMIT_TAG

PyPiBuildAndPublish:
    stage: pypi
    tags:
      - dind
    script:
      - docker pull $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA || true
      - docker run -e CI_JOB_TOKEN -e CI_PROJECT_ID $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA sh -c 'make pypi'
    rules:
      - if: $CI_COMMIT_TAG

CleanUp:
    stage: cleanup
    tags:
      - dind
    only:
      - master
      - merge_requests
      - tags
    script:
      - docker rmi -f $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA || true
    when: always
