stages:
    - build
    - test-py
    - test-js
    - versions
    - pypi

variables:
    BUILD_BOX_NAME: $CI_REGISTRY_IMAGE/build-box-gamma
    IMAGE_NAME: $BUILD_BOX_NAME/app:$CI_COMMIT_SHORT_SHA

Build:
    stage: build
    tags:
      - k8s-kaniko
    variables:
      KUBERNETES_CPU_REQUEST: "1200m"
      KUBERNETES_CPU_LIMIT: "2500m"
      KUBERNETES_MEMORY_REQUEST: "2Gi"
      KUBERNETES_MEMORY_LIMIT: "4Gi"
    only:
      - master
      - merge_requests
      - tags
    script:
      - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
        --destination "$IMAGE_NAME"
        --cache=true
        --use-new-run

Units:
    stage: test-py
    variables:
      GIT_STRATEGY: none
    tags:
      - k8s-runner
    image: $IMAGE_NAME
    only:
      - master
      - merge_requests
      - tags
    script:
      - cd /app && make test

ReactUnits:
    stage: test-js
    variables:
      GIT_STRATEGY: none
    tags:
      - k8s-runner
    image: $IMAGE_NAME
    only:
      - master
      - merge_requests
      - tags
    script:
      - cd /app && make jest

CheckVersion:
    stage: versions
    image: python:3.8
    script:
      - python check_version.py
    rules:
      - if: $CI_COMMIT_TAG

PyPiBuildAndPublish:
    stage: pypi
    variables:
      GIT_STRATEGY: none
    tags:
      - k8s-runner
    image: $IMAGE_NAME
    script:
      - cd /app && make pypi
    rules:
      - if: $CI_COMMIT_TAG
