# ============================================================================
# PYTEST CONFIGURATION FILE
# ============================================================================
# MORE OPTIONS:
#  addopts =
#  python_classes=*Test
#  python_functions=test_*
# ============================================================================

[pytest]
minversion    = 3.8
testpaths     = tests
python_files  = test_*.py
junit_family = xunit2
DJANGO_SETTINGS_MODULE = tests.conf.django_settings

markers =
    unittests: marks tests as unit test
